# Generated by Django 6.0.2 on 2026-02-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='read',
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
