# Generated by Django 6.0.2 on 2026-02-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_remove_boardmodel_read_boardmodel_read_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='read_count',
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
